apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: ecommerce
type: Opaque
# Valeurs encodées en base64 :
#   echo -n "mongouser"    | base64  →  bW9uZ291c2Vy
#   echo -n "MongoPass2024" | base64  →  TW9uZ29QYXNzMjAyNA==
data:
  MONGO_USERNAME: bW9uZ291c2Vy
  MONGO_PASSWORD: TW9uZ29QYXNzMjAyNA==
